### ISSUE TITLE
Feature Save API

### ISSUE THREAD

**Issue by zenic88** [damdev-study/question#4]
Feature 저장

POST 방식
URL : /image/feature
Header : Authorization
Body : 해당 카테고리의 u_id, feature 값 리스트

에러
400 BAD REQUEST
401 UNAUTHORIZED
503 SERVICE  UNAVAILABLE

한번에 50개까지 저장할 수 있다.

**Comment by wdhv2007** [comment]
주말부터 작업해볼게요

**Comment by wdhv2007** [comment]
작업하다가 SAVE랑 DELETE를 어떻게 처리해야 하는지 고민이네요
Mapping URL도 동일하고 테이블도 Result를 공유하는데 뭐가 다른지 이해가 잘 안가기 시작했어요

**Comment by zenic88** [comment]
extraction api 작업 완료한거야??
#13 커밋이 미완성 커밋밖에 없는데???

**Comment by wdhv2007** [comment]
SAVE는 아직 완성못했어요
첫 목록 50개 뽑아놓고 51번째부터는 어떻게 기억시켜야 할지 감이 안잡혀서요

**Comment by zenic88** [comment]
이건 안 닫았어 ㅋㅋ
그냥 50개만 처리하고 51개부터는 버리는걸로 하면 되지 않으려나~

**Comment by wdhv2007** [comment]
50개 이상이 나왔을땐 버리는 게 맞는거 같은데 그 다음 동작은 어디서부터 어디까지 불러와야 하는지 모르겠어요

**Comment by wdhv2007** [comment]
계속 50개씩 저장하면 처음에 50개만 저장되지 않을까요?

**Comment by zenic88** [comment]
그건 API 요청할때 처리를 해야하는거지 ㅋㅋㅋ

**Comment by wdhv2007** [comment]
요청을 보낼 때 기준이 되는 uid를 보내나요? 거기서 부터 50개를 처리하나요?

**Comment by zenic88** [comment]
흠..너가 이해를 못한거 같음..ㅋㅋㅋ

**Comment by wdhv2007** [comment]
네 이해가 안가여

**Comment by wdhv2007** [comment]
일단 request를 어디서 얻어오는지를 모르겠어요 ㅋㅋㅋㅋ
